# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('_bloom_timesTwo', PACKAGE = 'bloom', x)
}

create_bloom_parameters <- function() {
    .Call('_bloom_create_bloom_parameters', PACKAGE = 'bloom')
}

create_filter <- function() {
    .Call('_bloom_create_filter', PACKAGE = 'bloom')
}

bloom <- function() {
    .Call('_bloom_bloom', PACKAGE = 'bloom')
}

